name: build

on:
  push:
    branches:
      - "main"

env:
  DOCKERHUB_USERNAME: jacob1107

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     #- name: Clean Docker
     #   run: docker system prune --all --force --volumes
      - name: Build  and push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ./Dockerfile-BASE-BUILD-IMAGE  # 显式指定 Dockerfile
          platforms: linux/amd64
          tags: ${{ env.DOCKERHUB_USERNAME }}/backend-vllm:${{ steps.vars.outputs.sha_short }}
        
    
      
      
      # - name: Update helm values.yaml
      #   uses: fjogeleit/yaml-update-action@main
      #   with:
      #     valueFile: 'helm/values.yaml'
      #     commitChange: true
      #     branch: main
      #     message: 'Update Image Version to ${{ steps.vars.outputs.sha_short }}'
      #     changes: |
      #       {
      #         "backend.tag": "${{ steps.vars.outputs.sha_short }}",
      #         "frontend.tag": "${{ steps.vars.outputs.sha_short }}"
      #       }
